//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.02.10 at 03:11:58 EST 
//


package org.podval.imageio.jaxb;


/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="Directory">
 *   &lt;complexContent>
 *     &lt;extension base="{}Typed">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="record" type="{}SubRecord"/>
 *         &lt;element name="directory" type="{}SubDirectory"/>
 *         &lt;element name="makerNoteMarker" type="{}MakerNoteMarker"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Directory
    extends org.podval.imageio.jaxb.Typed
{


    java.util.List getEntries();


    /**
     * The following schema fragment specifies the expected content contained within this java content object.
     * <p>
     * <pre>
     * &lt;element name="makerNoteMarker" type="{}MakerNoteMarker"/>
     * </pre>
     * 
     */
    public interface MakerNoteMarker
        extends org.podval.imageio.jaxb.MakerNoteMarker
    {


    }


    /**
     * The following schema fragment specifies the expected content contained within this java content object.
     * <p>
     * <pre>
     * &lt;element name="record" type="{}SubRecord"/>
     * </pre>
     * 
     */
    public interface Record
        extends org.podval.imageio.jaxb.SubRecord
    {


    }

}
