//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.02.10 at 03:11:58 EST 
//


package org.podval.imageio.jaxb;


/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="Record">
 *   &lt;complexContent>
 *     &lt;extension base="{}Typed">
 *       &lt;choice>
 *         &lt;element name="field" type="{}Field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="enumeration" type="{}Enumeration" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="count" type="{}Count" />
 *       &lt;attribute name="vector" default="false" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Record
    extends org.podval.imageio.jaxb.Typed
{


    boolean isVector();

    void setVector(boolean value);

    boolean isSetVector();

    void unsetVector();

    org.podval.imageio.jaxb.Enumeration getEnumeration();

    void setEnumeration(org.podval.imageio.jaxb.Enumeration value);

    java.util.List getFields();

    Comparable getCount();

    void setCount(Comparable value);

}
