//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.02.10 at 03:11:58 EST 
//


package org.podval.imageio.jaxb;


/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="SubRecord">
 *   &lt;complexContent>
 *     &lt;extension base="{}Record">
 *       &lt;choice>
 *         &lt;element name="field" type="{}Field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="enumeration" type="{}Enumeration" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="tag" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SubRecord
    extends org.podval.imageio.jaxb.Record
{


    int getTag();

    void setTag(int value);

}
